import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("explore", "routes/explore.tsx"),
  route("discover", "routes/discover.tsx"),
  route("search", "routes/search.tsx"),
  route("api/autocomplete", "routes/api.autocomplete.tsx"),
  route("api/color-search", "routes/api.color-search.tsx"),
  route("api/explore-more", "routes/api.explore-more.tsx"),
  route("api/timeline", "routes/api.timeline.tsx"),
  route("timeline", "routes/timeline.tsx"),
  route("artwork/:id", "routes/artwork.tsx"),
  route("artist/:name", "routes/artist.tsx"),
  route("colors", "routes/colors.tsx"),
  route("walks", "routes/walks.tsx"),
  route("about", "routes/about.tsx"),
  route("api/feed", "routes/api.feed.tsx"),
  route("api/clip-search", "routes/api.clip-search.tsx"),
  route("mood-search", "routes/mood-search.tsx"),
  route("favorites", "routes/favorites.tsx"),
  route("color-match", "routes/color-match.tsx"),
  route("api/artworks", "routes/api.artworks.tsx"),
  route("compare", "routes/compare.tsx"),
  route("quiz", "routes/quiz.tsx"),
  route("api/compare-random", "routes/api.compare-random.tsx"),
  route("api/compare-search", "routes/api.compare-search.tsx"),
  route("api/quiz-match", "routes/api.quiz-match.tsx"),
] satisfies RouteConfig;
